### ISSUE TITLE
SIMD for extending

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [smarco/WFA2-lib#9]
In the current code you (and @lh3 also) compare 8chars / one 64bit int at a time. Have you tried using SIMD for this?

In particular, the operation is very similar to what absl/flat_hash_map does: do a compare of 16chars, convert the result to a 16bit mask, and count leading zeros.

16 vs 8 may not actually be such a big difference and SIMD of course makes things more complicated so it's hard to say whether it actually does much in the end.

Latency is also an important factor, since most of the time you call this off the main matching diagonal,  where you don't expect more than 8 matching characters anyway. I don't know whether simd has higher latency than the current code.

**Comment by smarco** [comment]
Yes, in fact, I did. But my experiments showed that the dominant number of cases do not extend more than a few bases. Using scalar 64bit instructions covers the vast majority of cases (see Itters/cell avg. in Table). Also, it performs very well on current OOO superscalar architectures. For the very few that "escape" and extend more than 8 bases, you could use SIMD, but I expect the performance improvement to be minimal.

![image](https://user-images.githubusercontent.com/2584429/160278183-d0ecc8c3-cb0d-4e20-893b-c5be9f751f89.png)

In any case, I think that using SIMD comparisons in all cases is not a good idea. Not because the specific instructions I need have more latency, but because they require more data to operate, which puts additional pressure on the memory architecture (L1, L2, etc...). On top of that, not all architectures/ISAs have a `ctlz` SIMD instruction. This would require architectural specializations of the code, which, for the moment, I don't need to have. Note that the compiler vectorizes the WFA to any supported architecture and vector length. The longer I can go without throwing specific intrinsics, the better. Not because I don't like low-level suff -- cause I really love it --, but because it's better for compatibility (e.g., I can run WFA vectorized for POWER9 or ARM without touching any part of the code).
